Function Initialize(url String) Uint64
10 IF EXISTS("INITIALIZED") THEN GOTO 40
15 SEND_ASSET_TO_ADDRESS(SIGNER(),1,SCID())
20 STORE("INITIALIZED",1)
30 STORE(".deroWeb",url)
35 STORE("OWNER",ADDRESS_STRING(SIGNER()))
40 RETURN 0
50 RETURN 1
End Function

Function SetUrl(url String, t String) Uint64
10 IF ASSETVALUE(SCID()) ==0 && SIGNER() != ADDRESS_RAW(LOAD("OWNER")) THEN GOTO 100
20 STORE(".deroWeb"+t,url)
30 SEND_ASSET_TO_ADDRESS(SIGNER(),ASSETVALUE(SCID()),SCID())
99 RETURN 0
100 RETURN 1
End Function

Function Display() Uint64
10 IF ASSETVALUE(SCID()) == 0 THEN GOTO 100
20 STORE("OWNER",ADDRESS_STRING(SIGNER()))
99 RETURN 0
100 RETURN 1
End Function

Function Retrieve() Uint64
10 IF SIGNER() != ADDRESS_RAW(LOAD("OWNER")) THEN GOTO 100
20 SEND_ASSET_TO_ADDRESS(SIGNER(),1,SCID())
99 RETURN 0
100 RETURN 1
End Function