Function Initialize(address String) Uint64
10 IF EXISTS("INITIALIZED") THEN GOTO 40
15 SEND_ASSET_TO_ADDRESS(ADDRESS_RAW(address),1,SCID())
20 STORE("INITIALIZED",1)
30 RETURN 0
40 RETURN 1
End Function